import AboutComp from "@/components/about/AboutComp"
import Hero from "@/components/hero/Hero"
import Layout from "@/components/layout/Layout"
import Quote from "@/components/quote/Quote"
import RecentPosts from "@/components/recentPosts/RecentPosts"
import Smile from "@/components/smile/Smile"
import Head from "next/head"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Hero />
        <RecentPosts />
        <Quote />
        <AboutComp />
        <Smile />
      </Layout>
    </>
  )
}
